### ISSUE TITLE
Sadly this won't work anymore

### ISSUE THREAD

**Issue by donno2048** [MakeNowJust/octocat-quine#1]

**Comment by makenowjust** [comment]
Happily, this works completely. (A created gist is [here](https://gist.github.com/MakeNowJust/7f677833383de0ad32c511498d84d402).)

I guess you configured 2FA for GitHub login.
In this case, you should input a personal access token instead of a password.
See [this official document](https://docs.github.com/en/github/authenticating-to-github/accessing-github-using-two-factor-authentication#authenticating-on-the-command-line-using-https).

**Comment by donno2048** [comment]
Well, I didn't enable 2FA, and it's not working...

But I guess if it's still working for you the problem is because of me...

Anyway, this is really cool
